In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("SuperStoreOrders.csv")

In [3]:
df.head()
df.shape

(51290, 21)

In [4]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("-", "_")
)

In [5]:
df.columns.tolist()

['order_id',
 'order_date',
 'ship_date',
 'ship_mode',
 'customer_name',
 'segment',
 'state',
 'country',
 'market',
 'region',
 'product_id',
 'category',
 'sub_category',
 'product_name',
 'sales',
 'quantity',
 'discount',
 'profit',
 'shipping_cost',
 'order_priority',
 'year']

In [6]:
df[["order_date", "ship_date"]].head()

  order_date ship_date
0   1/1/2011  6/1/2011
1   1/1/2011  8/1/2011
2   1/1/2011  5/1/2011
3   1/1/2011  5/1/2011
4   1/1/2011  8/1/2011

In [8]:
df["order_date"] = pd.to_datetime(
    df["order_date"],
    format="mixed",
    dayfirst=True
)

df["ship_date"] = pd.to_datetime(
    df["ship_date"],
    format="mixed",
    dayfirst=True
)

In [9]:
df[["order_date", "ship_date"]].head()

  order_date  ship_date
0 2011-01-01 2011-01-06
1 2011-01-01 2011-01-08
2 2011-01-01 2011-01-05
3 2011-01-01 2011-01-05
4 2011-01-01 2011-01-08

In [10]:
null_count = df.isnull().sum()

null_percent = (
    df.isnull().sum() / len(df) * 100
).round(2)

missing = pd.DataFrame({
    "missing_values": null_count,
    "missing_percent": null_percent
})

missing[missing["missing_values"] > 0]

Empty DataFrame
Columns: [missing_values, missing_percent]
Index: []

In [15]:
df[["sales", "quantity", "discount", "profit"]].describe()

              sales      quantity      discount        profit
count  51290.000000  51290.000000  51290.000000  51290.000000
mean     246.498440      3.476545      0.142908     28.641740
std      487.567175      2.278766      0.212280    174.424113
min        0.000000      1.000000      0.000000  -6599.978000
25%       31.000000      2.000000      0.000000      0.000000
50%       85.000000      3.000000      0.000000      9.240000
75%      251.000000      5.000000      0.200000     36.810000
max    22638.000000     14.000000      0.850000   8399.976000

In [14]:
df['sales'] = df['sales'].str.replace(',', '').astype(float)

In [17]:
print("sales <= 0:", (df["sales"] <= 0).sum())
print("Quantity <= 0:", (df["quantity"] <= 0).sum())
print("Negative Profit:", (df["profit"] < 0).sum())

sales <= 0: 1
Quantity <= 0: 0
Negative Profit: 12543

In [18]:
invalid_shipping = df[
    df["ship_date"] < df["order_date"]
]

invalid_shipping.shape

(0, 21)

In [19]:
df["year"] = df["order_date"].dt.year

df["quarter"] = df["order_date"].dt.quarter

df["month_number"] = df["order_date"].dt.month

df["month"] = df["order_date"].dt.month_name()

df["year_month"] = df["order_date"].dt.to_period("M").astype(str)

In [20]:
df[
    ["order_date", "year", "quarter",
     "month_number", "month", "year_month"]
].head()

  order_date  year  quarter  month_number    month year_month
0 2011-01-01  2011        1             1  January    2011-01
1 2011-01-01  2011        1             1  January    2011-01
2 2011-01-01  2011        1             1  January    2011-01
3 2011-01-01  2011        1             1  January    2011-01
4 2011-01-01  2011        1             1  January    2011-01

In [21]:
df["shipping_days"] = (
    df["ship_date"] - df["order_date"]
).dt.days

In [22]:
df["shipping_days"].describe()

count    51290.000000
mean         3.969370
std          1.729437
min          0.000000
25%          3.000000
50%          4.000000
75%          5.000000
max          7.000000
Name: shipping_days, dtype: float64

In [23]:
df[
    ["order_date", "ship_date", "shipping_days"]
].head()

  order_date  ship_date  shipping_days
0 2011-01-01 2011-01-06              5
1 2011-01-01 2011-01-08              7
2 2011-01-01 2011-01-05              4
3 2011-01-01 2011-01-05              4
4 2011-01-01 2011-01-08              7

Profit margin

In [25]:
df["profit_margin"] = (
    df["profit"] / df["sales"] * 100
).round(2)

In [26]:
df[
    ["sales", "profit", "profit_margin"]
].head()

   sales   profit  profit_margin
0  408.0  106.140          26.01
1  120.0   36.036          30.03
2   66.0   29.640          44.91
3   45.0  -26.055         -57.90
4  114.0   37.770          33.13

   sales   profit  profit_margin
0  408.0  106.140          26.01
1  120.0   36.036          30.03
2   66.0   29.640          44.91
3   45.0  -26.055         -57.90
4  114.0   37.770          33.13

In [28]:
df[
    [
        "year",
        "quarter",
        "month_number",
        "shipping_days",
        "profit_margin"
    ]
].describe()

C:\Users\Divyansh\AppData\Roaming\Python\Python314\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

               year       quarter  month_number  shipping_days  profit_margin
count  51290.000000  51290.000000  51290.000000   51290.000000       51290.00
mean    2012.777208      2.793235      7.522636       3.969370           -inf
std        1.098931      1.066015      3.300056       1.729437            NaN
min     2011.000000      1.000000      1.000000       0.000000           -inf
25%     2012.000000      2.000000      5.000000       3.000000           0.00
50%     2013.000000      3.000000      8.000000       4.000000          16.93
75%     2014.000000      4.000000     10.000000       5.000000          33.31
max     2014.000000      4.000000     12.000000       7.000000          58.28

In [29]:
df["year"].value_counts().sort_index()

year
2011     8998
2012    10962
2013    13799
2014    17531
Name: count, dtype: int64

In [30]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nMissing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

print("\nDate range:")
print(df["order_date"].min(), "to", df["order_date"].max())

Rows: 51290
Columns: 27

Duplicate rows:
0

Missing values:
Series([], dtype: int64)

Date range:
2011-01-01 00:00:00 to 2014-12-31 00:00:00

In [34]:
df.to_csv("Processed_SuperStoreOrders.csv")

In [35]:
df.columns.tolist()

['order_id',
 'order_date',
 'ship_date',
 'ship_mode',
 'customer_name',
 'segment',
 'state',
 'country',
 'market',
 'region',
 'product_id',
 'category',
 'sub_category',
 'product_name',
 'sales',
 'quantity',
 'discount',
 'profit',
 'shipping_cost',
 'order_priority',
 'order_year',
 'order_quarter',
 'month_number',
 'month_name',
 'year_month_text',
 'shipping_days',
 'profit_margin']

In [39]:
df.columns[df.columns.duplicated()].tolist()

[]

In [40]:
(df.columns.tolist())

['order_id',
 'order_date',
 'ship_date',
 'ship_mode',
 'customer_name',
 'segment',
 'state',
 'country',
 'market',
 'region',
 'product_id',
 'category',
 'sub_category',
 'product_name',
 'sales',
 'quantity',
 'discount',
 'profit',
 'shipping_cost',
 'order_priority',
 'order_year',
 'order_quarter',
 'month_number',
 'month_name',
 'year_month_text',
 'shipping_days',
 'profit_margin']

In [38]:
df.rename(columns={
    "year": "order_year",
    "quarter": "order_quarter",
    "month": "month_name",
    "year_month": "year_month_text"
}, inplace=True)

In [42]:
df.to_csv("Processed_SuperStoreOrders.csv",index=False)

In [43]:
df.iloc[625:640]

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,profit,shipping_cost,order_priority,order_year,order_quarter,month_number,month_name,year_month_text,shipping_days,profit_margin
625,ID-2011-47575,2011-02-15,2011-02-21,Standard Class,Christopher Martinez,Consumer,National Capital,Philippines,APAC,Southeast Asia,...,-172.1250,128.01,Low,2011,1,2,February,2011-02,6,-18.69
626,ID-2011-47575,2011-02-15,2011-02-21,Standard Class,Christopher Martinez,Consumer,National Capital,Philippines,APAC,Southeast Asia,...,-456.1740,118.63,Low,2011,1,2,February,2011-02,6,-36.94
627,IT-2011-1044550,2011-02-15,2011-02-20,Standard Class,Gary Zandusky,Consumer,Overijssel,Netherlands,EU,Central,...,-577.3200,78.18,Medium,2011,1,2,February,2011-02,5,-65.98
628,IT-2011-3264984,2011-02-15,2011-02-21,Standard Class,Tracy Poddar,Corporate,Andalusía,Spain,EU,South,...,-81.8640,60.76,Medium,2011,1,2,February,2011-02,6,-11.25
629,IT-2011-1044550,2011-02-15,2011-02-20,Standard Class,Gary Zandusky,Consumer,Overijssel,Netherlands,EU,Central,...,-499.9770,21.13,Medium,2011,1,2,February,2011-02,5,-183.14
630,CA-2011-121762,2011-02-15,2011-02-19,Standard Class,Marina Lichtenstein,Corporate,Washington,United States,US,West,...,4.7724,20.08,Medium,2011,1,2,February,2011-02,4,2.00
631,ID-2011-47575,2011-02-15,2011-02-21,Standard Class,Christopher Martinez,Consumer,National Capital,Philippines,APAC,Southeast Asia,...,-1.8450,16.42,Low,2011,1,2,February,2011-02,6,-1.35
632,CG-2011-6250,2011-02-15,2011-02-20,Standard Class,Trudy Brown,Consumer,Kinshasa,Democratic Republic of the Congo,Africa,Africa,...,4.0800,15.22,Medium,2011,1,2,February,2011-02,5,1.95
633,CA-2011-121762,2011-02-15,2011-02-19,Standard Class,Marina Lichtenstein,Corporate,Washington,United States,US,West,...,86.3892,13.45,Medium,2011,1,2,February,2011-02,4,36.00
634,CG-2011-6250,2011-02-15,2011-02-20,Standard Class,Trudy Brown,Consumer,Kinshasa,Democratic Republic of the Congo,Africa,Africa,...,63.2400,13.08,Medium,2011,1,2,February,2011-02,5,46.84
635,CG-2011-6250,2011-02-15,2011-02-20,Standard Class,Trudy Brown,Consumer,Kinshasa,Democratic Republic of the Congo,Africa,Africa,...,64.8000,10.16,Medium,2011,1,2,February,2011-02,5,41.01
636,CG-2011-6250,2011-02-15,2011-02-20,Standard Class,Trudy Brown,Consumer,Kinshasa,Democratic Republic of the Congo,Africa,Africa,...,1.3200,9.99,Medium,2011,1,2,February,2011-02,5,0.99
637,CG-2011-6250,2011-02-15,2011-02-20,Standard Class,Trudy Brown,Consumer,Kinshasa,Democratic Republic of the Congo,Africa,Africa,...,23.8200,9.19,Medium,2011,1,2,February,2011-02,5,24.06
638,IT-2011-3264984,2011-02-15,2011-02-21,Standard Class,Tracy Poddar,Corporate,Andalusía,Spain,EU,South,...,19.0800,8.53,Medium,2011,1,2,February,2011-02,6,15.02
639,CG-2011-6250,2011-02-15,2011-02-20,Standard Class,Trudy Brown,Consumer,Kinshasa,Democratic Republic of the Congo,Africa,Africa,...,9.4800,6.19,Medium,2011,1,2,February,2011-02,5,9.98

In [44]:
text_cols = [
    "order_id", "ship_mode", "customer_name",
    "segment", "state", "country", "market",
    "region", "product_id", "category",
    "sub_category", "product_name",
    "order_priority"
]

for col in text_cols:
    print(col, df[col].astype(str).str.len().max())

order_id 15
ship_mode 14
customer_name 22
segment 11
state 36
country 32
market 6
region 14
product_id 16
category 15
sub_category 11
product_name 127
order_priority 8

In [45]:
print("DataFrame shape:", df.shape)
print("DataFrame rows:", len(df))

DataFrame shape: (51290, 27)
DataFrame rows: 51290

In [ ]:
text_cols = [
    "order_id", "ship_mode", "customer_name",
    "segment", "state", "country", "market",
    "region", "product_id", "category",
    "sub_category", "product_name",
    "order_priority"
]

for col in text_cols:
    print(col, df[col].astype(str).str.len().max())

order_id 15
ship_mode 14
customer_name 22
segment 11
state 36
country 32
market 6
region 14
product_id 16
category 15
sub_category 11
product_name 127
order_priority 8

In [50]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "mysql+mysqlconnector://root:12345678@localhost/revenue_intelligence"
)

In [51]:
from sqlalchemy import text

with engine.connect() as conn:
    print("Database:", conn.execute(
        text("SELECT DATABASE()")
    ).scalar())

    print("MySQL rows:", conn.execute(
        text("SELECT COUNT(*) FROM stg_sales")
    ).scalar())

Database: revenue_intelligence
MySQL rows: 631

In [52]:
with engine.begin() as conn:
    conn.execute(text("TRUNCATE TABLE stg_sales"))

print("Old records removed.")

Old records removed.

In [53]:
with engine.connect() as conn:
    count = conn.execute(
        text("SELECT COUNT(*) FROM stg_sales")
    ).scalar()

print("Rows:", count)

Rows: 0

In [54]:
print(df.shape)

(51290, 27)

In [55]:
try:
    rows = df.to_sql(
        name="stg_sales",
        con=engine,
        if_exists="append",
        index=False,
        chunksize=1000
    )

    print("Import completed successfully!")
    print("Returned:", rows)

except Exception as e:
    print("IMPORT FAILED")
    print(type(e).__name__)
    print(e)

IMPORT FAILED
ProgrammingError
(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'inf' in 'field list'
[SQL: INSERT INTO stg_sales (order_id, order_date, ship_date, ship_mode, customer_name, segment, state, country, market, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit, shipping_cost, order_priority, order_year, order_quarter, month_number, month_name, year_month_text, shipping_days, profit_margin) VALUES (%(order_id)s, %(order_date)s, %(ship_date)s, %(ship_mode)s, %(customer_name)s, %(segment)s, %(state)s, %(country)s, %(market)s, %(region)s, %(product_id)s, %(category)s, %(sub_category)s, %(product_name)s, %(sales)s, %(quantity)s, %(discount)s, %(profit)s, %(shipping_cost)s, %(order_priority)s, %(order_year)s, %(order_quarter)s, %(month_number)s, %(month_name)s, %(year_month_text)s, %(shipping_days)s, %(profit_margin)s)]
[parameters: [{'order_id': 'MX-2014-120530', 'order_date': datetime.datetime(2014, 6, 20, 0, 0), 'ship_date': datetime.datetime(2014, 6, 26, 0, 0), 'ship_mode': 'Standard Class', 'customer_name': 'Justin Ritter', 'segment': 'Corporate', 'state': 'Santiago de Cuba', 'country': 'Cuba', 'market': 'LATAM', 'region': 'Caribbean', 'product_id': 'OFF-BI-10003372', 'category': 'Office Supplies', 'sub_category': 'Binders', 'product_name': 'Ibico Binding Machine, Durable', 'sales': 35.0, 'quantity': 1, 'discount': 0.0, 'profit': 0.34, 'shipping_cost': 2.88, 'order_priority': 'Medium', 'order_year': 2014, 'order_quarter': 2, 'month_number': 6, 'month_name': 'June', 'year_month_text': '2014-06', 'shipping_days': 6, 'profit_margin': 0.97}, {'order_id': 'ID-2014-26960', 'order_date': datetime.datetime(2014, 6, 20, 0, 0), 'ship_date': datetime.datetime(2014, 6, 23, 0, 0), 'ship_mode': 'Second Class', 'customer_name': 'Tiffany House', 'segment': 'Corporate', 'state': 'New South Wales', 'country': 'Australia', 'market': 'APAC', 'region': 'Oceania', 'product_id': 'OFF-SU-10004727', 'category': 'Office Supplies', 'sub_category': 'Supplies', 'product_name': 'Stiletto Letter Opener, Easy Grip', 'sales': 27.0, 'quantity': 1, 'discount': 0.1, 'profit': 9.3, 'shipping_cost': 2.19, 'order_priority': 'Medium', 'order_year': 2014, 'order_quarter': 2, 'month_number': 6, 'month_name': 'June', 'year_month_text': '2014-06', 'shipping_days': 3, 'profit_margin': 34.44}, {'order_id': 'CA-2014-138870', 'order_date': datetime.datetime(2014, 6, 20, 0, 0), 'ship_date': datetime.datetime(2014, 6, 24, 0, 0), 'ship_mode': 'Standard Class', 'customer_name': 'George Ashbrook', 'segment': 'Consumer', 'state': 'California', 'country': 'United States', 'market': 'US', 'region': 'West', 'product_id': 'FUR-FU-10002396', 'category': 'Furniture', 'sub_category': 'Furnishings', 'product_name': 'DAX Copper Panel Document Frame, 5 x 7 Size', 'sales': 50.0, 'quantity': 4, 'discount': 0.0, 'profit': 21.1344, 'shipping_cost': 2.14, 'order_priority': 'Medium', 'order_year': 2014, 'order_quarter': 2, 'month_number': 6, 'month_name': 'June', 'year_month_text': '2014-06', 'shipping_days': 4, 'profit_margin': 42.27}, {'order_id': 'MX-2014-120530', 'order_date': datetime.datetime(2014, 6, 20, 0, 0), 'ship_date': datetime.datetime(2014, 6, 26, 0, 0), 'ship_mode': 'Standard Class', 'customer_name': 'Justin Ritter', 'segment': 'Corporate', 'state': 'Santiago de Cuba', 'country': 'Cuba', 'market': 'LATAM', 'region': 'Caribbean', 'product_id': 'OFF-LA-10000738', 'category': 'Office Supplies', 'sub_category': 'Labels', 'product_name': 'Avery File Folder Labels, Adjustable', 'sales': 14.0, 'quantity': 3, 'discount': 0.0, 'profit': 6.42, 'shipping_cost': 1.98, 'order_priority': 'Medium', 'order_year': 2014, 'order_quarter': 2, 'month_number': 6, 'month_name': 'June', 'year_month_text': '2014-06', 'shipping_days': 6, 'profit_margin': 45.86}, {'order_id': 'ID-2014-11098', 'order_date': datetime.datetime(2014, 6, 20, 0, 0), 'ship_date': datetime.datetime(2014, 6, 25, 0, 0), 'ship_mode': 'Standard Class', 'customer_name': 'Neil Ducich', 'segment': 'Corporate', 'state': 'Western Australia', 'country': 'Australia', 'market': 'APAC', 'region': 'Oceania', 'product_id': 'OFF-LA-10000624', 'category': 'Office Supplies', 'sub_category': 'Labels', 'product_name': 'Hon File Folder Labels, 5000 Label Set', 'sales': 24.0, 'quantity': 3, 'discount': 0.1, 'profit': 7.281, 'shipping_cost': 1.78, 'order_priority': 'Medium', 'order_year': 2014, 'order_quarter': 2, 'month_number': 6, 'month_name': 'June', 'year_month_text': '2014-06', 'shipping_days': 5, 'profit_margin': 30.34}, {'order_id': 'TX-2014-4340', 'order_date': datetime.datetime(2014, 6, 20, 0, 0), 'ship_date': datetime.datetime(2014, 6, 25, 0, 0), 'ship_mode': 'Standard Class', 'customer_name': 'Jim Epp', 'segment': 'Corporate', 'state': 'Mary', 'country': 'Turkmenistan', 'market': 'EMEA', 'region': 'EMEA', 'product_id': 'FUR-RUB-10002945', 'category': 'Furniture', 'sub_category': 'Furnishings', 'product_name': 'Rubbermaid Photo Frame, Duo Pack', 'sales': 16.0, 'quantity': 1, 'discount': 0.7, 'profit': -17.637, 'shipping_cost': 1.71, 'order_priority': 'High', 'order_year': 2014, 'order_quarter': 2, 'month_number': 6, 'month_name': 'June', 'year_month_text': '2014-06', 'shipping_days': 5, 'profit_margin': -110.23}, {'order_id': 'CA-2014-138870', 'order_date': datetime.datetime(2014, 6, 20, 0, 0), 'ship_date': datetime.datetime(2014, 6, 24, 0, 0), 'ship_mode': 'Standard Class', 'customer_name': 'George Ashbrook', 'segment': 'Consumer', 'state': 'California', 'country': 'United States', 'market': 'US', 'region': 'West', 'product_id': 'OFF-PA-10004438', 'category': 'Office Supplies', 'sub_category': 'Paper', 'product_name': 'Xerox 1907', 'sales': 25.0, 'quantity': 2, 'discount': 0.0, 'profit': 11.5432, 'shipping_cost': 1.36, 'order_priority': 'Medium', 'order_year': 2014, 'order_quarter': 2, 'month_number': 6, 'month_name': 'June', 'year_month_text': '2014-06', 'shipping_days': 4, 'profit_margin': 46.17}, {'order_id': 'ID-2014-11098', 'order_date': datetime.datetime(2014, 6, 20, 0, 0), 'ship_date': datetime.datetime(2014, 6, 25, 0, 0), 'ship_mode': 'Standard Class', 'customer_name': 'Neil Ducich', 'segment': 'Corporate', 'state': 'Western Australia', 'country': 'Australia', 'market': 'APAC', 'region': 'Oceania', 'product_id': 'OFF-FA-10001010', 'category': 'Office Supplies', 'sub_category': 'Fasteners', 'product_name': 'Stockwell Clamps, Metal', 'sales': 17.0, 'quantity': 1, 'discount': 0.1, 'profit': 3.075, 'shipping_cost': 1.28, 'order_priority': 'Medium', 'order_year': 2014, 'order_quarter': 2, 'month_number': 6, 'month_name': 'June', 'year_month_text': '2014-06', 'shipping_days': 5, 'profit_margin': 18.09}  ... displaying 10 of 1000 total bound parameter sets ...  {'order_id': 'CA-2014-127460', 'order_date': datetime.datetime(2014, 7, 11, 0, 0), 'ship_date': datetime.datetime(2014, 7, 15, 0, 0), 'ship_mode': 'Standard Class', 'customer_name': 'Frank Gastineau', 'segment': 'Home Office', 'state': 'Illinois', 'country': 'United States', 'market': 'US', 'region': 'Central', 'product_id': 'OFF-ST-10004340', 'category': 'Office Supplies', 'sub_category': 'Storage', 'product_name': 'Fellowes Mobile File Cart, Black', 'sales': 298.0, 'quantity': 6, 'discount': 0.2, 'profit': 26.1156, 'shipping_cost': 16.31, 'order_priority': 'High', 'order_year': 2014, 'order_quarter': 3, 'month_number': 7, 'month_name': 'July', 'year_month_text': '2014-07', 'shipping_days': 4, 'profit_margin': 8.76}, {'order_id': 'RS-2014-9190', 'order_date': datetime.datetime(2014, 7, 11, 0, 0), 'ship_date': datetime.datetime(2014, 7, 15, 0, 0), 'ship_mode': 'Standard Class', 'customer_name': 'Stephanie Ulpright', 'segment': 'Home Office', 'state': 'Irkutsk', 'country': 'Russia', 'market': 'EMEA', 'region': 'EMEA', 'product_id': 'TEC-HP -10004451', 'category': 'Technology', 'sub_category': 'Copiers', 'product_name': 'HP Ink, Laser', 'sales': 129.0, 'quantity': 1, 'discount': 0.0, 'profit': 25.74, 'shipping_cost': 15.5, 'order_priority': 'High', 'order_year': 2014, 'order_quarter': 3, 'month_number': 7, 'month_name': 'July', 'year_month_text': '2014-07', 'shipping_days': 4, 'profit_margin': 19.95}]]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [56]:

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    inf_count = np.isinf(df[col]).sum()
    
    if inf_count > 0:
        print(col, ":", inf_count)

profit_margin : 1

In [57]:
df[np.isinf(df["profit_margin"])][
    ["order_id", "sales", "profit", "profit_margin"]
]

             order_id  sales  profit  profit_margin
40017  US-2014-102288    0.0   -1.11           -inf

In [58]:
import numpy as np

df["profit_margin"] = df["profit_margin"].replace(
    [np.inf, -np.inf],
    np.nan
)

In [59]:
df.loc[40017, [
    "order_id",
    "sales",
    "profit",
    "profit_margin"
]]

order_id         US-2014-102288
sales                       0.0
profit                    -1.11
profit_margin               NaN
Name: 40017, dtype: object

In [60]:
numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    count = np.isinf(df[col]).sum()
    if count > 0:
        print(col, count)

In [61]:
df = df.astype(object).where(pd.notnull(df), None)

In [62]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("TRUNCATE TABLE stg_sales"))

In [63]:
with engine.connect() as conn:
    print(
        conn.execute(
            text("SELECT COUNT(*) FROM stg_sales")
        ).scalar()
    )

0

In [64]:
df.to_sql(
    name="stg_sales",
    con=engine,
    if_exists="append",
    index=False,
    chunksize=1000
)

-52

In [65]:
with engine.connect() as conn:
    mysql_rows = conn.execute(
        text("SELECT COUNT(*) FROM stg_sales")
    ).scalar()

print("Pandas:", len(df))
print("MySQL:", mysql_rows)

Pandas: 51290
MySQL: 51290